### PR TITLE
Feature/api integration

### LINKED ISSUE #51: test

### LINKED ISSUE #52: [element] test

### PR DESCRIPTION
**Pull request by kedziersky**

### CODE REVIEW

**Comment by kedziersky** [comment]
Resolves: #50

**Comment by kamilkedzierski** [comment]
#50

**Comment by kamilkedzierski** [comment]
#50

**Comment by kamilkedzierski** [comment]
#50

**Comment by kamilkedzierski** [comment]
#51

**Review by kamilkedzierski — APPROVED** [review]

**Review by kamilkedzierski — APPROVED** [review]

**Review by kamilkedzierski — APPROVED** [review]

**Review by kamilkedzierski — APPROVED** [review]

**Review by kamilkedzierski — APPROVED** [review]

**Review by kamilkedzierski — APPROVED** [review]

**Review by kamilkedzierski — APPROVED** [review]

**Review by kamilkedzierski — APPROVED** [review]

**Review by kamilkedzierski — APPROVED** [review]

**Review by kamilkedzierski — APPROVED** [review]

**Review by kamilkedzierski — APPROVED** [review]

**Review by kamilkedzierski — APPROVED** [review]

**Review by kamilkedzierski — APPROVED** [review]

**Review by kamilkedzierski — APPROVED** [review]

**Review by kamilkedzierski — APPROVED** [review]

**Review by kamilkedzierski — APPROVED** [review]
Approved: #51

**Comment by kamilkedzierski** [comment]
Approved: #51

**Comment by kamilkedzierski** [comment]
approved #51

**Comment by kamilkedzierski** [comment]
approved #51

**Comment by kamilkedzierski** [comment]
Approved #51

**Comment by kamilkedzierski** [comment]
approved #51

**Comment by kamilkedzierski** [comment]
Approved #51

**Comment by kamilkedzierski** [comment]
#40

**Comment by kamilkedzierski** [comment]
Resolves: #71

**Comment by kamilkedzierski** [comment]
Resolves #71

**Comment by kamilkedzierski** [comment]
Resolves #71

**Comment by kamilkedzierski** [comment]
Resolves #71

**Comment by kamilkedzierski** [comment]
resolves #71

**Comment by kamilkedzierski** [comment]
resloves #71

**Comment by kamilkedzierski** [comment]
resolves #71

**Comment by kamilkedzierski** [comment]
resolves #71

**Comment by kamilkedzierski** [comment]
resolves #71

**Comment by kamilkedzierski** [comment]
approved #71

**Comment by kamilkedzierski** [comment]
review #71

**Comment by kamilkedzierski** [comment]
resolves #71

**Comment by kamilkedzierski** [comment]
resolves #71 approved #71

**Pull request closed without merging**
